export const events = [
  {
    title: 'Tech Innovators Summit 2025',
    image: '/images/event1.png',
    slug: 'tech-innovators-summit-2025',
    location: 'San Francisco, CA',
    date: 'March 15, 2025',
    time: '09:00 AM',
  },
  {
    title: 'Global Hackathon Series',
    image: '/images/event2.png',
    slug: 'global-hackathon-series',
    location: 'New York, NY',
    date: 'April 22, 2025',
    time: '10:00 AM',
  },
  {
    title: 'AI & Machine Learning Expo',
    image: '/images/event3.png',
    slug: 'ai-ml-expo',
    location: 'Austin, TX',
    date: 'May 10, 2025',
    time: '08:30 AM',
  },
  {
    title: 'Web Dev Conference',
    image: '/images/event4.png',
    slug: 'web-dev-conference',
    location: 'London, UK',
    date: 'June 05, 2025',
    time: '09:00 AM',
  },
  {
    title: 'Cybersecurity World Forum',
    image: '/images/event5.png',
    slug: 'cybersecurity-world-forum',
    location: 'Berlin, Germany',
    date: 'July 18, 2025',
    time: '11:00 AM',
  },
  {
    title: 'Cloud Computing Summit',
    image: '/images/event6.png',
    slug: 'cloud-computing-summit',
    location: 'Seattle, WA',
    date: 'August 25, 2025',
    time: '09:30 AM',
  },
]
